#!/usr/bin/env bash
# Single source of version truth is the VERSION file at the repo root.
# This script writes that file and the generated Swift constant.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <major.minor.patch>" >&2
  exit 2
fi

version="$1"
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "VERSION must be semver X.Y.Z (got '$version')" >&2
  exit 1
fi

printf '%s\n' "$version" > VERSION

cat > Sources/PhotonCore/PhotonVersion.swift <<EOF
/// Generated by Scripts/bump-version.sh. Do not edit by hand.
public enum PhotonVersion: Sendable {
  public static let string = "$version"
}
EOF

echo "Set version to $version"
echo "Next: commit, merge to main, tag v${version}, push the tag."
