#!/usr/bin/env bash
# Single source of version truth is the VERSION file at the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <major.minor.patch>" >&2
  exit 2
fi

version="$1"
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "VERSION must be semver X.Y.Z (got '$version')" >&2
  exit 1
fi

printf '%s\n' "$version" > VERSION

python3 - "$version" <<'PY'
import pathlib, re, sys
version = sys.argv[1]
path = pathlib.Path("crates/photon-core/src/version.rs")
path.write_text(
    "/// Generated by Scripts/bump-version.sh. Do not edit by hand.\n"
    f'pub const PHOTON_VERSION: &str = "{version}";\n'
)
cargo = pathlib.Path("Cargo.toml")
text = cargo.read_text()
updated, n = re.subn(
    r'(?m)^version = "[0-9]+\.[0-9]+\.[0-9]+"$',
    f'version = "{version}"',
    text,
    count=1,
)
if n != 1:
    raise SystemExit("failed to patch workspace.package.version in Cargo.toml")
cargo.write_text(updated)
print(f"Wrote crates/photon-core/src/version.rs and Cargo.toml version = {version}")
PY

echo "Set version to $version"
echo "Next: commit, merge to main, tag v${version}, push the tag."
